version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: chairo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kadomazim@89
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  # <- Add restart option here

  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chairo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Kadomazim@89
    ports:
      - "8080:8080"
    restart: unless-stopped  # <- Add restart option here

volumes:
  postgres_data:
